### ISSUE TITLE
카악

### ISSUE THREAD

**Issue by HyopangWorld** [CaptainWonJong/MySampleApp#2]
퉤

**Comment by CaptainWonJong** [comment]
@HyopangWorld 
여러분 이 사람이 SQI의 미래를 책임질 사람입니다!!!!!!!!!!!!!!!!!!!!!!!!!!
우리 모두 응원합시다ㅏㅏㅏㅏㅏㅏㅏㅏㅏ

**Comment by HyopangWorld** [comment]
..........
